# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master", "main"]

jobs:
  test:
    runs-on: ubuntu-latest

    # services: ブロックは削除する

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- ここから追記 ---
      - name: Start services with Docker Compose
        run: docker-compose -f docker-compose.dev.yml up --build -d
      # --- ここまで追記 ---

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
             requirements.txt
             requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # dev-requirements.txtにrequestsを追加しておく必要があります
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      # LibreOfficeのインストールは不要になります（extractionコンテナ内で実行されるため）
      # - name: Install LibreOffice (headless) ...

      - name: Wait for services to be ready
        run: |
          # サービスが起動するまで少し待機（最長60秒）
          docker-compose -f docker-compose.dev.yml exec -T extraction bash -c 'until curl -s http://localhost:8080/health; do sleep 1; done'

      - name: Run unit tests
        run: pytest tests/test_exparso_pptx.py

      - name: Run end-to-end tests
        run: |
          export EXTRACTION_API_URL="http://localhost:8080"
          export MLFLOW_TRACKING_URI="http://localhost:5000"
          pytest tests/extraction_e2e.py
