# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: ["**"] # Run on all branches
  pull_request:
    branches: ["master", "main"] # Run on pull requests to master or main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      extraction:
        build: ./backend/extraction_service
        ports:
          - 8080:8080
      mlflow:
        image: ghcr.io/mlflow/mlflow:v2.12.1 # 修正済みの正しいタグを使用
        ports:
          - 5000:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Aligning with devcontainer.json
          cache: "pip"
          cache-dependency-path: |
             requirements.txt
             requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install application requirements if requirements.txt exists
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install development dependencies
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Install LibreOffice (headless)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libreoffice-core libreoffice-impress libreoffice-writer

      - name: Run pytest
        run: pytest -q tests/
        # Added 'tests/' to specify the target directory for pytest for clarity.

      - name: Run end-to-end tests
        run: |
          # テストコードがサービスに接続できるよう、環境変数を設定
          export EXTRACTION_API_URL="http://localhost:8080"
          export MLFLOW_TRACKING_URI="http://localhost:5000"
          pytest tests/extraction_e2e.py

# Contains AI-generated edits.
